In [10]:
import pandas as pd
from sklearn import model_selection

In [3]:
train = pd.read_csv('../input/mnist_train.csv')
test = pd.read_csv('../input/mnist_test.csv')

In [6]:
df = pd.concat([train,test])

In [8]:
df = df.reset_index(drop = True)

In [11]:
df['kfold'] = -1

In [14]:
kf = model_selection.KFold(n_splits = 5)

In [23]:
df = df.sample(frac=1).reset_index(drop=True)

In [24]:
df

,label,1x1,1x2,1x3,1x4,1x5,1x6,1x7,1x8,1x9,...,28x20,28x21,28x22,28x23,28x24,28x25,28x26,28x27,28x28,kfold
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,-1
1,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,-1
2,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,-1
3,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,-1
4,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69995,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,-1
69996,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,-1
69997,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,-1
69998,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,-1
69999,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,-1

In [30]:
for fold, y in enumerate(kf.split(X=df)):
    df.loc[val_, 'kfold'] = fold

In [32]:
df.to_csv('../input/mnist_folds.csv')

In [42]:
df.drop(columns = ['label','kfold'],axis=1)

,1x1,1x2,1x3,1x4,1x5,1x6,1x7,1x8,1x9,1x10,...,28x19,28x20,28x21,28x22,28x23,28x24,28x25,28x26,28x27,28x28
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
69996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
69997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
69998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
69999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [33]:
import argparse

In [34]:
parser = argparse.ArgumentParser()

In [35]:
parser.add_argument("--fold", type=int)
args = parser.parse_args()
args

usage: ipykernel_launcher.py [-h] [--fold FOLD]
ipykernel_launcher.py: error: unrecognized arguments: -f C:\Users\owenz\AppData\Roaming\jupyter\runtime\kernel-1fb5dd13-870e-4750-ad49-2331ea476e0b.json

SystemExit: 2

C:\Users\owenz\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3334: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)